# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143zot_GtLiPsUaO3pVAaWyRqnhQSyw3a
"""

import pandas as pd
baza={
    "FISH":[ "Bakirov E", "Ashurov G", "Komilov B", "Hadjiyev H", "Bozorov Q", "Bakirova E", "Ashurova G", "Komilova B", "Hadjiyeva H", "Bozorova Q" ],
    "Yoshi":[  "16", "16", "16", "16", "16", "16", "16", "16", "16", "16" ],
    "Jinsi":[  "Erkak", "Erkak", "Erkak", "Erkak", "Erkak", "Ayol", "Ayol", "Ayol", "Ayol", "Ayol" ],
    "Maktabi":[  "15-maktab", "15-maktab", "15-maktab", "15-maktab", "15-maktab", "15-maktab", "15-maktab", "15-maktab", "15-maktab", "15-maktab" ],
    "Manzili":[ "Farg'ona sh", "Farg'ona sh", "Farg'ona sh", "Farg'ona sh", "Farg'ona sh", "Qo'qon", "Qo'qon","Qo'qon","Qo'qon","Qo'qon"  ],
    "Tel raqami":[ "88 111 22 33", "88 111 22 33", "88 111 22 33", "88 111 22 33", "88 111 22 33", "33 444 55 66", "33 444 55 66", "33 444 55 66", "33 444 55 66", "33 444 55 66"  ],
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']== "Erkak"]
print(filtr)

# Creating DataFrame
db = pd.DataFrame(baza)
# Sorting the DataFrame by 'FISH' column alphabetically
sorted_db = db.sort_values(by='FISH') # Displaying the sorted DataFrame
print("DataFrame sorted by FISH:")
print(sorted_db)